spring.application.name=api

#Tomcat configuration
server.port=9090

#Log level configuration
logging.level.root=INFO
logging.level.com.openclassrooms=INFO
logging.level.org.springframework.boot.autoconfigure.h2=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

#H2 Configuration
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.h2.console.settings.web-allow-others=true

#Postgres configuration (Désactivé pour utiliser H2)
spring.datasource.url=jdbc:postgresql://localhost:5432/Entreprise
spring.datasource.username=postgres
spring.datasource.password=FullstackODC
spring.datasource.driver-class-name=org.postgresql.Driver

# H2 Configuration (Ajouté pour le test)
# spring.datasource.url=jdbc:h2:mem:odc_db
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# === Swagger ===
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# === CORS ===
app.cors.allowed-origins=http://localhost:3000,http://localhost:3001,http://localhost:49293,http://localhost

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Commenté pour H2
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000